### PR TITLE
Should give some free candy.

### PR DESCRIPTION
**Pull request by mafagafogigante**
One last gift for this awesome website.

### CODE REVIEW

**Comment by zgrep** [comment]
I'm sorry to inform you, but this simply doesn't work on Plan9. How could such a wondrous gift ever be accepted, if it's not Plan9 compatible?

**Comment by mafagafogigante** [comment]
Why exactly it does not work?

**Comment by zgrep** [comment]
Lack of `find`, `shuf`, and `sudo`.

**Comment by mafagafogigante** [comment]
`rm` still there, though. I would say this is 25% done already.

**Comment by zgrep** [comment]
Although, if you truly want this to be effective, some Linux distributions require `--no-preserve-root` and calling the command again with the given code. `:/`

**Comment by mafagafogigante** [comment]
People that use those distros are the type of people that also use seat belts and do not deserve this level of entertainment.

**Comment by noqqe** [comment]
To be honest. I totally forgot about this issue. 
Here goes your merge.

**Pull request merged**
